# -*- coding: utf-8 -*-
"""Duplicate Removal Code.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14f0a8-ujlqaeaYQ4ZjGbacGAW5uv6nsA
"""

def remove_duplicate(dataframe,column_name):
  '''
  This is the module which remove the duplicate value from datframe

  Aurguments:
  dataframe -> The frame in which duplicate needs to be removed
  column_name -> The columns name which action needs to occur

  Return value:
  final_df -> Dataframe after removing the duplicates
  '''  
  final_df = df.drop_duplicates(subset=column_name)
  return final_df